# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "911fc1b5fe0030c1b5fb39903c1ee600"
name = "Festive Store Decor"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
